package cn.aorise.database.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.aorise.database.db.entity.LangEntity;

import cn.aorise.database.db.LangEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig langEntityDaoConfig;

    private final LangEntityDao langEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        langEntityDaoConfig = daoConfigMap.get(LangEntityDao.class).clone();
        langEntityDaoConfig.initIdentityScope(type);

        langEntityDao = new LangEntityDao(langEntityDaoConfig, this);

        registerDao(LangEntity.class, langEntityDao);
    }
    
    public void clear() {
        langEntityDaoConfig.clearIdentityScope();
    }

    public LangEntityDao getLangEntityDao() {
        return langEntityDao;
    }

}
